include(CheckIPOSupported)

function(sc2opt_apply_hardening target)
    if(SC2OPT_ENABLE_ASAN)
        if(MSVC)
            target_compile_options(${target} PRIVATE /fsanitize=address)
            target_link_options(${target} PRIVATE /fsanitize=address)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=address)
        else()
            message(FATAL_ERROR "SC2OPT_ENABLE_ASAN requested on unsupported compiler ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endif()

    if(SC2OPT_ENABLE_UBSAN)
        if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
            target_link_options(${target} PRIVATE -fsanitize=undefined)
        else()
            message(FATAL_ERROR "SC2OPT_ENABLE_UBSAN requested on unsupported compiler ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endif()

    if(SC2OPT_ENABLE_AVX2)
        if(MSVC)
            target_compile_options(${target} PRIVATE /arch:AVX2)
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            target_compile_options(${target} PRIVATE -mavx2)
        else()
            message(FATAL_ERROR "SC2OPT_ENABLE_AVX2 requested on unsupported compiler ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endif()

    if(SC2OPT_ENABLE_LTO)
        check_ipo_supported(RESULT _sc2opt_ipo_supported OUTPUT _sc2opt_ipo_error LANGUAGES CXX)
        if(NOT _sc2opt_ipo_supported)
            message(FATAL_ERROR "SC2OPT_ENABLE_LTO requested but IPO/LTO is unsupported: ${_sc2opt_ipo_error}")
        endif()
        set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
    endif()

    if(SC2OPT_PGO_GENERATE)
        if(MSVC)
            target_compile_options(${target} PRIVATE /GL)
            target_link_options(${target} PRIVATE /LTCG /GENPROFILE)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            if(SC2OPT_PGO_PROFILE_DIR)
                set(_sc2opt_pgo_generate "-fprofile-generate=${SC2OPT_PGO_PROFILE_DIR}")
            else()
                set(_sc2opt_pgo_generate "-fprofile-generate")
            endif()
            target_compile_options(${target} PRIVATE ${_sc2opt_pgo_generate})
            target_link_options(${target} PRIVATE ${_sc2opt_pgo_generate})
        else()
            message(FATAL_ERROR "SC2OPT_PGO_GENERATE currently supports MSVC and GNU only")
        endif()
    endif()

    if(SC2OPT_PGO_USE)
        if(MSVC)
            target_compile_options(${target} PRIVATE /GL)
            target_link_options(${target} PRIVATE /LTCG /USEPROFILE)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            if(NOT SC2OPT_PGO_PROFILE_DIR)
                message(FATAL_ERROR "GNU SC2OPT_PGO_USE requires SC2OPT_PGO_PROFILE_DIR")
            endif()
            set(_sc2opt_pgo_use "-fprofile-use=${SC2OPT_PGO_PROFILE_DIR}")
            target_compile_options(${target} PRIVATE ${_sc2opt_pgo_use} -fprofile-correction)
            target_link_options(${target} PRIVATE ${_sc2opt_pgo_use} -fprofile-correction)
        else()
            message(FATAL_ERROR "SC2OPT_PGO_USE currently supports MSVC and GNU only")
        endif()
    endif()
endfunction()
